name: anaesthesics-project
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fair=2.2.2
  - jupyter
  - jupyterlab
  - jupytext
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - xarray